name: Release
on:
  push:
    branches:
      - main
jobs:
  semanticRelease:
    name: Release the Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: https://npm.pkg.github.com/
      - name: Install Dependencies
        run: |
          npm ci
          npm run docs:build
          git add docs -f
          git commit -m "gh-pages update!"
          git subtree push --prefix docs origin gh-pages


