name: On Every Commit (Lint)
on: push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.6"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - run: npm run lint
