name: On Every Commit (Lint)
on: push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      # - name: Cache Linters/Formatters
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/trunk
      #     key: trunk-${{ runner.os }}
      - name: Trunk Check
        uses: trunk-io/trunk-action@v0.3.0-beta
